### ISSUE TITLE
Invalid Public Key

### ISSUE THREAD

**Issue by winstxnhdw** [mcdallas/rust-discord-bot#2]
Hey @mcdallas!

I am using your [verification.rs](https://github.com/mcdallas/rust-discord-bot/blob/master/src/verification.rs) to verify the interaction request but I hit the `InvalidPublicKey` error every single time. I have printed out the public key, signature and timestamp and everything checks out fine.

**Comment by mcdallas** [comment]
Afaik discord sends two request during initial handshake, one valid to test that you verify valid keys and one invalid to test that you reject invalid keys. Maybe that's the case?

**Comment by winstxnhdw** [comment]
I am aware. Do you think it could be the escape characters in the body? When I print my body, it looks like this on CloudWatch.

```rs
"{\\\"application_id\\\":\\\"10808372312321368\\\",\\\"id\\\":\\\"1233255646456\\\",\\\"token\\\":\\\"sometokenvalue\\\",\\\"type\\\":1,\\\"user\\\":{\\\"avatar\\\":\\\"79e08ef8e5ed37367f00557995\\\",\\\"avatar_decoration\\\":null,\\\"discriminator\\\":\\\"3866\\\",\\\"display_name\\\":null,\\\"id\\\":\\\"1233255646456\\\",\\\"public_flags\\\":0,\\\"username\\\":\\\"asd\\\"},\\\"version\\\":1}"
```

**Comment by winstxnhdw** [comment]
Okay, it seems the problem is the escape characters.
